<?php
/**
 * Template Part: Sección Videos - Carrusel Editable con ACF
 */

// Obtener valores de ACF
$section_title = dr_cabello_get_option('video_section_title', '¿Cómo es un trasplante capilar?');
$section_subtitle = dr_cabello_get_option('video_section_subtitle', 'Conoce de primera mano los procedimientos, testimonios y resultados que respaldan nuestra experiencia de más de 12 años transformando vidas.');
$videos = dr_cabello_get_option('videos', array());

// Si no hay videos en ACF, usar datos por defecto (compatibilidad)
if (empty($videos)) {
    // Los videos se cargarán desde JavaScript con datos por defecto
    $use_default_videos = true;
} else {
    $use_default_videos = false;
    // Pasar videos de ACF a JavaScript
    $video_data_for_js = array();
    $video_count = 0;
    
    foreach ($videos as $video) {
        $video_count++;
        
        // Determinar URL del video según tipo
        $video_url = '';
        if ($video['type'] === 'youtube' && !empty($video['video_url_youtube'])) {
            $video_url = $video['video_url_youtube'];
        } elseif ($video['type'] === 'local' && !empty($video['video_file_local'])) {
            $video_url = $video['video_file_local'];
        }
        
        // Preparar características
        $features = array();
        if (!empty($video['features'])) {
            foreach ($video['features'] as $feature) {
                if (!empty($feature['text'])) {
                    $features[] = $feature['text'];
                }
            }
        }
        
        $video_data_for_js[] = array(
            'id' => 'video-' . $video_count,
            'title' => $video['title'] ?? '',
            'description' => $video['description'] ?? '',
            'category' => $video['category'] ?? 'Procedimientos',
            'duration' => $video['duration'] ?? '0:00',
            'thumbnail' => $video['thumbnail'] ?? '',
            'videoUrl' => $video_url,
            'type' => $video['type'] ?? 'youtube',
            'features' => $features,
        );
    }
}
?>

<!-- Video Carousel Section -->
<section id="videos" class="video-carousel-section reveal">
    <div class="container">
        <!-- Section Header -->
        <div class="video-carousel-header">
            <h2><?php echo esc_html($section_title); ?></h2>
            <p class="video-carousel-subtitle">
                <?php echo esc_html($section_subtitle); ?>
            </p>
        </div>

        <!-- Carousel Container -->
        <div class="video-carousel-container">
            <!-- Counter -->
            <div class="carousel-counter">
                <span class="current">1</span> / <?php echo $use_default_videos ? '6' : count($videos); ?>
            </div>

            <!-- Carousel Wrapper -->
            <div class="video-carousel-wrapper">
                <div class="video-carousel-track">
                    <!-- Slides will be generated by JavaScript -->
                </div>

                <!-- Carousel Controls -->
                <div class="carousel-controls">
                    <button class="carousel-btn carousel-btn-prev" aria-label="Video anterior">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <polyline points="15 18 9 12 15 6"/>
                        </svg>
                    </button>

                    <div class="carousel-indicators">
                        <?php 
                        $total_videos = $use_default_videos ? 6 : count($videos);
                        for ($i = 1; $i <= $total_videos; $i++): 
                        ?>
                            <button class="carousel-indicator <?php echo $i === 1 ? 'active' : ''; ?>" 
                                    aria-label="Video <?php echo $i; ?>"></button>
                        <?php endfor; ?>
                    </div>

                    <button class="carousel-btn carousel-btn-next" aria-label="Siguiente video">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <polyline points="9 18 15 12 9 6"/>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>

<?php if (!$use_default_videos): ?>
<script>
    // Pasar datos de videos de ACF a JavaScript
    window.WP_VIDEO_DATA = <?php echo json_encode($video_data_for_js); ?>;
</script>
<?php endif; ?>
